[tool.poetry]
name = "five-factor-e"
version = "v1.13.1"
description = "Big 5 IPIP-NEO Personality Traits"
authors = ["Ederson Corbari <e@NeuroQuest.ai>"]
readme = "README.md"
packages = [{include = "five_factor_e"}]

[tool.poetry.dependencies]
python = "^3.10"
coverage = "^7.3.1"
plotext = "^5.2.8"
isort = "^5.12.0"
black = "^23.9.1"
setuptools = "^70.3.0"
fastapi = ">=0.111.0"
uvicorn = "^0.23.2"
sqlalchemy = "^2.0.20"
psycopg2-binary = "^2.9.7"
pydantic = "^2.3.0"
pyjwt = "^2.11.0"
passlib = "^1.7.4"
bcrypt = "^5.0.0"
python-multipart = "^0.0.22"
alembic = "^1.18.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "ruff (>=0.15.5,<0.16.0)",
    "mypy (>=1.19.1,<2.0.0)"
]
