"""Initial migration

Revision ID: 1ed683ba8fce
Revises: 
Create Date: 2026-03-07 22:24:17.068659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed683ba8fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('personality_profiles_user_id_key'), 'personality_profiles', type_='unique')
    op.create_index(op.f('ix_personality_profiles_user_id'), 'personality_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_topic_id'), 'posts', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_topic_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_index(op.f('ix_personality_profiles_user_id'), table_name='personality_profiles')
    op.create_unique_constraint(op.f('personality_profiles_user_id_key'), 'personality_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
